"HW2 is completed"
Lokion13/otus-golang pull request #2
Opened 2023-12-11 08:39 UTC by Lokion13

## Домашнее задание №2 «Распаковка строки»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [+] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [+] Я запустил `go mod tidy`.
- [+] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [+] Я сравнил объем кода с объемом авторского решения. [Зачем сверять объем кода?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D1%81%D0%B2%D0%B5%D1%80%D1%8F%D1%82%D1%8C-%D0%BE%D0%B1%D1%8A%D0%B5%D0%BC-%D0%BA%D0%BE%D0%B4%D0%B0)
  - unpack.go ~45 строк для задания без звездочки // если не использовать лишние переносы строки
  - unpack.go ~75 строк для задания со звездочкой

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2023-12-13 05:46 UTC, ityulkanov requested changes

2023-12-13 05:46 UTC, ityulkanov commented on hw02_unpack_string/unpack.go
> +		rInt, ErrIsDigit := strconv.Atoi(string(inputStr[i]))
Я бы не рекомендовал основывать логику на ошибках. Есть же простой способ проверить является ли руна числом - проверить находится ли её значение между 0 и 9, всё что не удовлетворяет этому условию является символом, который мы распаковываем по условиям ниже.

2023-12-13 05:46 UTC, ityulkanov commented on hw02_unpack_string/unpack_test.go
>  		// uncomment if task with asterisk completed
Добавьте, пожалуйста пару тройку тест кейсов с символами юникода - смайлами или флагами, чтобы проверить что распаковка работает как и должна и приму.

2023-12-15 06:16 UTC, Lokion13 commented on hw02_unpack_string/unpack.go
> +		rInt, ErrIsDigit := strconv.Atoi(string(inputStr[i]))
Вы знаете, я действительно перемудрил) переписал код

2023-12-15 06:17 UTC, Lokion13 commented on hw02_unpack_string/unpack_test.go
>  		// uncomment if task with asterisk completed
добавил

2023-12-15 09:13 UTC, ityulkanov approved these changes

2023-12-15 09:16 UTC, merged